name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/capture-decran-2023-07-07-a-1701-2-bg.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1718-1.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1720-1.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1719-1.png
    - assets/page-1/images/cellular-connection.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/battery-Sb1.png
    - assets/page-1/images/group-148.png
    - assets/page-1/images/cellular-connection-tj9.png
    - assets/page-1/images/group-34.png
    - assets/page-1/images/group-45.png
    - assets/page-1/images/icon-left.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/wifi-hrF.png
    - assets/page-1/images/icon-left-fJX.png
    - assets/page-1/images/wifi-8rK.png
    - assets/page-1/images/cellular-connection-my9.png
    - assets/page-1/images/battery-Shu.png
    - assets/page-1/images/cellular-connection-BUT.png
    - assets/page-1/images/icon-left-DZZ.png
    - assets/page-1/images/battery-QGP.png
    - assets/page-1/images/cellular-connection-H6X.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/wifi-csy.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1701-2-bg-XV9.png
    - assets/page-1/images/group.png
    - assets/page-1/images/vector-eqD.png
    - assets/page-1/images/frame.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1701-1.png
    - assets/page-1/images/group-7.png
    - assets/page-1/images/battery-4hM.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1718-1-Kb5.png
    - assets/page-1/images/battery-jM9.png
    - assets/page-1/images/auto-group-542t.png
    - assets/page-1/images/wifi-irb.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1723-1.png
    - assets/page-1/images/wifi-yCb.png
    - assets/page-1/images/vector-47Z.png
    - assets/page-1/images/wifi-DFM.png
    - assets/page-1/images/cellular-connection-mGs.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1739-1.png
    - assets/page-1/images/vector-1Zh.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1720-1-wkB.png
    - assets/page-1/images/battery-9Yj.png
    - assets/page-1/images/icon-left-2Md.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1723-1-FQ3.png
    - assets/page-1/images/battery-bu9.png
    - assets/page-1/images/pattern.png
    - assets/page-1/images/wifi-KcB.png
    - assets/page-1/images/cellular-connection-CR5.png
    - assets/page-1/images/group-11.png
    - assets/page-1/images/cellular-connection-vkP.png
    - assets/page-1/images/group-Mts.png
    - assets/page-1/images/cellular-connection-dbV.png
    - assets/page-1/images/group-146.png
    - assets/page-1/images/battery-phu.png
    - assets/page-1/images/logo.png
    - assets/page-1/images/group-147.png
    - assets/page-1/images/icon-left-U4w.png
    - assets/page-1/images/addfill0wght300grad0opsz40-1.png
    - assets/page-1/images/battery-mEP.png
    - assets/page-1/images/cellular-connection-iQX.png
    - assets/page-1/images/wifi-g6T.png
    - assets/page-1/images/vector-dA7.png
    - assets/page-1/images/vector-7jV.png
    - assets/page-1/images/cellular-connection-eum.png
    - assets/page-1/images/wifi-p3Z.png
    - assets/page-1/images/cellular-connection-eVm.png
    - assets/page-1/images/vector-odZ.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1701-1-K1Z.png
    - assets/page-1/images/battery-g6K.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1723-1-H9H.png
    - assets/page-1/images/icon-light-chevronleft.png
    - assets/page-1/images/vector-khd.png
    - assets/page-1/images/vector-jHH.png
    - assets/page-1/images/group-34-qHh.png
    - assets/page-1/images/group-51.png
    - assets/page-1/images/wifi-msV.png
    - assets/page-1/images/icon-light-chevronleft-J1V.png
    - assets/page-1/images/wifi-def.png
    - assets/page-1/images/vector-3Z9.png
    - assets/page-1/images/rectangle-187.png
    - assets/page-1/images/icon-left-GcF.png
    - assets/page-1/images/pattern-aoH.png
    - assets/page-1/images/addfill0wght300grad0opsz40-1-czs.png
    - assets/page-1/images/vector-L9V.png
    - assets/page-1/images/vector-ijh.png
    - assets/page-1/images/cellular-connection-xAj.png
    - assets/page-1/images/frame-NXq.png
    - assets/page-1/images/wifi-Q2K.png
    - assets/page-1/images/battery-SqM.png
    - assets/page-1/images/battery-ZLs.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1719-1-5QK.png
    - assets/page-1/images/group-193.png
    - assets/page-1/images/auto-group-p6tz.png
    - assets/page-1/images/wifi-BDR.png
    - assets/page-1/images/vector-Brf.png
    - assets/page-1/images/icon-left-Ghd.png
    - assets/page-1/images/icon-Mnw.png
    - assets/page-1/images/icon-RNo.png
    - assets/page-1/images/cellular-connection-U6j.png
    - assets/page-1/images/vector-Fqy.png
    - assets/page-1/images/cellular-connection-PaF.png
    - assets/page-1/images/auto-group-b4tz.png
    - assets/page-1/images/fumagine-1.png
    - assets/page-1/images/group-34-duy.png
    - assets/page-1/images/battery-55h.png
    - assets/page-1/images/cellular-connection-Xk3.png
    - assets/page-1/images/battery-KfV.png
    - assets/page-1/images/battery-kgF.png
    - assets/page-1/images/wifi-mFm.png
    - assets/page-1/images/cellular-connection-5S7.png
    - assets/page-1/images/wifi-SK9.png
    - assets/page-1/images/wifi-a5u.png
    - assets/page-1/images/wifi-i5V.png
    - assets/page-1/images/wifi-4v3.png
    - assets/page-1/images/cellular-connection-DU3.png
    - assets/page-1/images/icon-left-W31.png
    - assets/page-1/images/cellular-connection-v8X.png
    - assets/page-1/images/degats-xanthomonas-fruit1-1.png
    - assets/page-1/images/icon-left-bMR.png
    - assets/page-1/images/icon-left-6m5.png
    - assets/page-1/images/icon-left-dYb.png
    - assets/page-1/images/icon-left-dLb.png
    - assets/page-1/images/degats-xanthomonas-fruit1-1-3fm.png
    - assets/page-1/images/fumagine-1-1tj.png
    - assets/page-1/images/battery-Tvw.png
    - assets/page-1/images/cellular-connection-Joh.png
    - assets/page-1/images/wifi-wYb.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1720-1-QhM.png
    - assets/page-1/images/battery-TZZ.png
    - assets/page-1/images/wifi-ZrX.png
    - assets/page-1/images/battery-dtK.png
    - assets/page-1/images/icon-left-4Ph.png
    - assets/page-1/images/cellular-connection-z2T.png
    - assets/page-1/images/capture-decran-2023-07-07-a-1723-2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
